import unittest
from . import rel as rel
from _typeshed import Incomplete

unittest2: Incomplete
possible_build_dir: Incomplete

class EventTest(unittest.TestCase):
    def skip(self, reason) -> None: ...
    call_back_ran: bool
    def setUp(self) -> None: ...
    def test_timeout(self) -> None: ...
    def test_timeout2(self) -> None: ...
    def test_signal(self) -> None: ...
    def test_signal2(self) -> None: ...
    def test_read(self) -> None: ...
    def test_read2(self) -> None: ...
    def test_exception(self) -> None: ...
    def test_abort(self) -> None: ...
    def test_callback_exception(self) -> None: ...
    call_back_ran_a: bool
    call_back_ran_b: bool
    def test_thread(self) -> None: ...
