from _typeshed import Incomplete

def notice(*lines) -> None: ...
def exit() -> None: ...
def error(msg, *lines) -> None: ...

RT_MEDIA: Incomplete
RT_USAGE: Incomplete

class Timer:
    count: int
    goal: Incomplete
    media: Incomplete
    def __init__(self, s, m, h, interval: int = ..., mediapath=...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def update(self): ...
    def alarm(self) -> None: ...

def timerCLI() -> None: ...
