from _typeshed import Incomplete

listeners: Incomplete
happenings: Incomplete

def emit(channel, *args, **kwargs): ...
def ask(channel, *args, **kwargs): ...
def listen(channel, cb) -> None: ...
def when(event, cb, *args, **kwargs) -> None: ...
def transpire(event) -> None: ...
